apiVersion: v1
kind: Service
metadata:
  name: opensearch-headless
  namespace: opencti
  labels:
    app: opensearch-cluster
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
  selector:
    app: opensearch-cluster