---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-api
  namespace: {{ .Values.namespace }}
  labels:
    name: minio-api
spec:
  rules:
  - host: {{ .Values.ingress.api }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: minio-api
            port: 
              number: 9000
