apiVersion: v1
kind: Service
metadata:
  name: minio-web
  namespace: {{ .Values.namespace }}
  labels:
    app: minio-cluster
spec:
  selector:
    app: minio-cluster
  ports:
  - name: minio-web
    port: 9001
    protocol: TCP