apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-web
  namespace: {{ .Values.namespace }}
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
  - name: rabbitmq-web
    protocol: TCP
    port: 15672
    targetPort: 15672
    nodePort: 30080