apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: opencti
  labels:
    app: opensearch-cluster
spec:
  selector:
    app: opensearch-cluster
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 30920