apiVersion: v1
kind: Service
metadata:
  name: minio-api
  namespace: {{ .Values.namespace }}
  labels:
    app: minio-cluster
spec:
  selector:
    app: minio-cluster
  ports:
  - name: minio-api
    port: 9000
    protocol: TCP