apiVersion: v1
kind: Service
metadata:
  name: opensearch-web
  namespace: opencti
  labels:
    app: opensearch
spec:
  selector:
    app: opensearch
  type: NodePort
  ports:
  - name: opensearch-web
    protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 30920