apiVersion: v1
kind: Service
metadata:
  name: analyzer
  namespace: opencti
  labels:
    app: opensearch
spec:
  selector:
    app: opensearch
  type: NodePort
  ports:
  - name: analyzer
    protocol: TCP
    port: 9600
    targetPort: 9600
    nodePort: 30960