apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-cluster
  namespace: {{.Values.namespace}}
  labels:
    app: rabbitmq-cluster
spec:
  selector:
    matchLabels:
      app: rabbitmq-cluster
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitmq-cluster
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/{{ .Values.node_role }}
                operator: Exists
      tolerations:
        - key: {{ .Values.node_tolerations }}
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: rabbitmq-cluster
        image: rabbitmq:management
        env:
        - name: RABBITMQ_ENABLE_QUORUM_QUEUES
          value: "true"  # Включаем Quorum Queues
        - name: RABBITMQ_DEFAULT_USER
          value: "{{ .Values.rabbitmq_default_user }}"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
                name: secret-rabbitmq
                key: rabbitmq_default_pass
        ports:
          - name: rabbitmq-web
            protocol: TCP
            containerPort: 15672
          - name: rabbitmq-api
            protocol: TCP
            containerPort: 5672
        volumeMounts:
        - name: rabbitmq-storage
          mountPath: "/var/lib/rabbitmq"
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-storage
      namespace: opencti
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn-hdd
      resources:
        requests:
          storage: 5Gi